-- Two retailers, one customer each, one PENDING payment request for A.
-- Deterministic UUIDs so the tests can reference them.

INSERT INTO auth.users (id, email) VALUES
  ('00000000-0000-4000-8000-00000000000a', 'a@tele.local'),
  ('00000000-0000-4000-8000-00000000000b', 'b@tele.local'),
  ('00000000-0000-4000-8000-0000000000ad', 'admin@admin.local');

INSERT INTO profiles (user_id, role) VALUES
  ('00000000-0000-4000-8000-00000000000a', 'retailer'),
  ('00000000-0000-4000-8000-00000000000b', 'retailer'),
  ('00000000-0000-4000-8000-0000000000ad', 'super_admin');

INSERT INTO retailers (id, auth_user_id, name, username, is_active) VALUES
  ('10000000-0000-4000-8000-00000000000a', '00000000-0000-4000-8000-00000000000a', 'RETAILER A', 'reta', true),
  ('10000000-0000-4000-8000-00000000000b', '00000000-0000-4000-8000-00000000000b', 'RETAILER B', 'retb', true);

-- Customer of A, and customer of B. The EMI schedule is generated by the
-- portal's own trigger, so the fixture exercises real business logic.
INSERT INTO customers (id, retailer_id, customer_name, mobile, imei,
                       purchase_value, down_payment, purchase_date,
                       emi_amount, emi_tenure, emi_due_day, first_emi_charge_amount, status)
VALUES
  ('20000000-0000-4000-8000-00000000000a', '10000000-0000-4000-8000-00000000000a',
   'CUST OF A', '9000000001', '111111111111111', 12000, 2000, '2025-01-05', 1000, 10, 5, 500, 'RUNNING'),
  ('20000000-0000-4000-8000-00000000000b', '10000000-0000-4000-8000-00000000000b',
   'CUST OF B', '9000000002', '222222222222222', 12000, 2000, '2025-01-05', 1000, 10, 5, 500, 'RUNNING');

-- A PENDING collection request belonging to retailer A, awaiting super-admin
-- approval. This is the object SEC-001 lets a retailer self-approve.
INSERT INTO payment_requests (id, customer_id, retailer_id, submitted_by, status, mode,
                              total_emi_amount, fine_amount, first_emi_charge_amount, total_amount)
VALUES ('30000000-0000-4000-8000-00000000000a',
        '20000000-0000-4000-8000-00000000000a',
        '10000000-0000-4000-8000-00000000000a',
        '00000000-0000-4000-8000-00000000000a',
        'PENDING', 'CASH', 1000, 0, 0, 1000);

INSERT INTO payment_request_items (payment_request_id, emi_schedule_id, emi_no, amount)
SELECT '30000000-0000-4000-8000-00000000000a', id, emi_no, amount
FROM emi_schedule
WHERE customer_id = '20000000-0000-4000-8000-00000000000a' AND emi_no = 1;

-- A real auto-login token, so the anon-read test measures ROWS LEAKED rather
-- than merely "the query did not error".
INSERT INTO customer_app_tokens (customer_id, token, is_active)
VALUES ('20000000-0000-4000-8000-00000000000a', 'secret-token-value', true);
